// File: clock_block.v
// Generated by MyHDL 0.10
// Date: Mon May 27 19:13:54 2019


`timescale 1ns/10ps

module clock_block (
    clock
);


output [0:0] clock;
reg [0:0] clock;




initial begin: CLOCK_BLOCK_CLOCK_DRIVE
    while (1'b1) begin
        # 10;
        clock <= 1;
        # 10;
        clock <= 0;
    end
end

endmodule
